### ISSUE TITLE
Popup problems...

### ISSUE THREAD

**Issue by ArthurChf** [EvolSoft/ServerAuth#101]
Hi,
First, thanks to your awesome plugin, it's work ! 😉
But there are two problems...
Well, the first : The register's popups and the login's popups repeat all the time, untils we are authentificated... And I would like to display thé popups at once ! Would that bé possible ?
The second problem : when we switch on the authentication via IP adress, the plugin still asks me to login (it doesn't happen all the time). How can I fix this ?
Thanks ahead for your answers ! (and sorry for m'y bad english : I'm french and I speak french !)
Cordially, Arthur.

**Comment by Flavius12** [comment]
_First answer:_
Popups? What do you mean? ServerAuth doesn't have register and login popups
_Second answer:_
This happens because almost all ISP (internet service providers) give to their customers dynamic IPs (obviously you can also ask your ISP to give a static IP). This means that your IP changes dynamically (after some time or if you disconnect your device from your router). So when you log in with a different IP, ServerAuth can't log you in obviously

**Comment by ArthurChf** [comment]
Thanks for answer !
For the first problem, I expressed myself badly...
These are not popups, but messages.(that we can change).
Cordially, Arthur.

**Comment by Flavius12** [comment]
From your ServerAuth configuration change login/register `message-interval` to a greater number (for example if you set it to 60 you will get the message every minute only)
See the wiki for more info:
https://github.com/EvolSoft/ServerAuth/wiki/ServerAuth-Installation#configuration

**Comment by ArthurChf** [comment]
OK great thanks !!!
Thanks again for your awesome plugin !
Cordially.
