### ISSUE TITLE
Can SimpleAuth's data be moved to ServerAuth?

### ISSUE THREAD

**Issue by ghost** [EvolSoft/ServerAuth#44]
I think this plugin is better than simple auth and i want to change to use this plugin, but my server has nearly 18000 accounts so i affraid to lose it all, how can move players's password from simpleauth to serverauth? Ths :)

**Comment by HotFireyDeath** [comment]
Unfortunately, I believe there isn't a verified way to transport player logins from SimpleAuth to ServerAuth.

**Comment by Flavius12** [comment]
Actually there isn't a way to migrate SimpleAuth data to ServerAuth. When I'm a bit free, I may start to make a script which migrates SimpleAuth data to ServerAuth but I can't promise nothing. However you can also move SimpleAuth data to ServerAuth manually but I don't recommend to do this because if you don't copy data correctly, ServerAuth plugin may not work.
BTW if you switch to ServerAuth without migrating old SimpleAuth accounts it's not a big problem. Your server players will only have to register again on your server

**Comment by ghost** [comment]
But in my survival server, if players have to register again, they can steal others's accounts :(

**Comment by Patra3** [comment]
Something you will have to deal with manually as part of switching an authorization plugin.

**Comment by PEMapModder** [comment]
@HotFireyDeath nobody ever migrates accounts by hand, unless it is not a server at all (unless it has very few accounts).

**Comment by PEMapModder** [comment]
You should consider adding support to use multiple hash algos, such as SimpleAuth

**Comment by Flavius12** [comment]
hash algorithms can be changed in ServerAuth config. Actually supported algorithms are all PHP supported algorithms (You can get the list with this function http://php.net/manual/en/function.hash-algos.php)

**Comment by PEMapModder** [comment]
@flavius12 I know. But I said multiple, not other. SimpleAuth uses multiple algos, combined with XOR, and with alternating salt/password order. ServerAuth doesn't seem to support this.

**Comment by Flavius12** [comment]
It seems a bit complicated...
